"""
100-Agent Workforce Registry — real definitions for every worker.

Each agent has:
- identity (id, name, domain, type, version)
- purpose (what it does)
- inputs (what events/metrics it consumes)
- tools (which tools it may use, with permission levels)
- trigger_conditions (when it activates)
- decision_policy (how it decides)
- rate_limits (max executions)
- resource_limits (max concurrent tasks)
- verification_method (how results are verified)
- rollback_policy (what happens on failure)

NO AGENT IS A DUMMY. Every entry has real purpose, real tools, and real constraints.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class AgentType(str, Enum):
    DETERMINISTIC = "deterministic"
    AI_REASONING = "ai_reasoning"
    RULE_ENGINE = "rule_engine"
    ANOMALY_DETECTOR = "anomaly_detector"
    COORDINATOR = "coordinator"


class AgentDomain(str, Enum):
    SECURITY = "security"
    MODERATION = "moderation"
    PERFORMANCE = "performance"
    RELIABILITY = "reliability"
    DATA = "data"
    USER_EXPERIENCE = "user_experience"
    COMMUNITY = "community"
    ANALYTICS = "analytics"
    PLATFORM_OPS = "platform_ops"
    AI_GOVERNANCE = "ai_governance"


class ToolPermission(str, Enum):
    READ = "read"
    ANALYZE = "analyze"
    RECOMMEND = "recommend"
    WRITE = "write"
    DELETE = "delete"
    SECURITY = "security"
    INFRASTRUCTURE = "infrastructure"


@dataclass(frozen=True)
class AgentDef:
    agent_id: str
    name: str
    domain: str
    agent_type: str
    purpose: str
    events: tuple[str, ...] = ()
    tools: tuple[str, ...] = ()
    tool_permissions: tuple[str, ...] = ()
    trigger_conditions: tuple[str, ...] = ()
    decision_policy: str = "observe_react"
    max_runs_per_hour: int = 10
    max_concurrent: int = 1
    confidence_threshold: float = 0.5
    verification_method: str = "metric_comparison"
    rollback_policy: str = "log_and_alert"
    version: str = "1.0.0"


# ─── DOMAIN A: SECURITY (1-10) ──────────────────────────────────────

SECURITY_AGENTS = [
    AgentDef(
        agent_id="sec-001",
        name="Threat Monitor",
        domain="security",
        agent_type="anomaly_detector",
        purpose="Continuous monitoring of platform for security threats, unusual access patterns, and attack signatures",
        events=("API_REQUEST", "USER_LOGIN", "SUSPICIOUS_ACTIVITY", "SECURITY_ANOMALY"),
        tools=("read_service_metrics", "check_spam_signals", "create_alert", "record_finding"),
        trigger_conditions=("suspicious_activity", "security_anomaly", "rate_spike", "error_spike"),
        decision_policy="threshold_alert",
        max_runs_per_hour=30,
        confidence_threshold=0.6,
    ),
    AgentDef(
        agent_id="sec-002",
        name="Suspicious Session Detector",
        domain="security",
        agent_type="rule_engine",
        purpose="Detects anomalous session behavior: rapid location changes, impossible travel, concurrent sessions from different IPs",
        events=("USER_LOGIN", "API_REQUEST", "SESSION_CREATED"),
        tools=("read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("new_session", "session_anomaly"),
        decision_policy="pattern_match",
        max_runs_per_hour=50,
    ),
    AgentDef(
        agent_id="sec-003",
        name="Account Risk Analyst",
        domain="security",
        agent_type="ai_reasoning",
        purpose="Evaluates account risk based on behavior history, velocity, and reputation signals",
        events=("USER_CREATED", "USER_LOGIN", "POST_CREATED", "COMMENT_CREATED"),
        tools=("read_service_metrics", "check_spam_signals", "record_finding"),
        trigger_conditions=("new_account", "suspicious_velocity", "risk_score_change"),
        decision_policy="score_threshold",
        confidence_threshold=0.7,
    ),
    AgentDef(
        agent_id="sec-004",
        name="Spam Detection Worker",
        domain="security",
        agent_type="deterministic",
        purpose="Real-time spam detection using velocity checks, content similarity, and link analysis",
        events=("POST_CREATED", "COMMENT_CREATED", "USER_CREATED"),
        tools=("check_spam_signals", "analyze_content_risk", "detect_duplicates", "create_alert", "record_finding"),
        trigger_conditions=("new_content", "velocity_spike", "duplicate_detected"),
        decision_policy="composite_score",
        max_runs_per_hour=100,
    ),
    AgentDef(
        agent_id="sec-005",
        name="Abuse Pattern Analyst",
        domain="security",
        agent_type="ai_reasoning",
        purpose="Identifies complex abuse patterns that span multiple accounts and time periods",
        events=("SPAM_DETECTED", "ABUSE_DETECTED", "REPORT_CREATED"),
        tools=("read_service_metrics", "check_spam_signals", "record_finding", "create_alert"),
        trigger_conditions=("abuse_detected", "report_cluster"),
        confidence_threshold=0.75,
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="sec-006",
        name="Authentication Monitor",
        domain="security",
        agent_type="rule_engine",
        purpose="Monitors authentication flows for brute force, credential stuffing, and session hijacking",
        events=("USER_LOGIN", "USER_LOGOUT", "API_ERROR"),
        tools=("read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("login_failure_spike", "session_anomaly"),
        decision_policy="threshold_alert",
        max_runs_per_hour=40,
    ),
    AgentDef(
        agent_id="sec-007",
        name="Permission Auditor",
        domain="security",
        agent_type="deterministic",
        purpose="Audits access control and authorization for admin endpoints and sensitive operations",
        events=("API_REQUEST", "CONFIGURATION_CHANGED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("admin_action", "permission_change", "periodic_audit"),
        max_runs_per_hour=5,
        verification_method="access_log_comparison",
    ),
    AgentDef(
        agent_id="sec-008",
        name="Security Event Correlator",
        domain="security",
        agent_type="ai_reasoning",
        purpose="Correlates multiple low-severity events into high-severity incidents",
        events=("SECURITY_ANOMALY", "SUSPICIOUS_ACTIVITY", "SPAM_DETECTED"),
        tools=("read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("event_cluster", "escalation_needed"),
        confidence_threshold=0.8,
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="sec-009",
        name="Enforcement Verifier",
        domain="security",
        agent_type="deterministic",
        purpose="Verifies that security enforcement actions were actually applied and effective",
        events=("DEPLOYMENT_COMPLETED", "CONFIGURATION_CHANGED"),
        tools=("verify_fix", "read_service_metrics", "record_finding"),
        trigger_conditions=("enforcement_action", "post_action_verify"),
        verification_method="before_after_comparison",
    ),
    AgentDef(
        agent_id="sec-010",
        name="Security Incident Coordinator",
        domain="security",
        agent_type="coordinator",
        purpose="Coordinates multi-agent response to security incidents, manages escalation",
        events=("SECURITY_ANOMALY", "ABUSE_DETECTED", "SERVICE_DEGRADED"),
        tools=("create_alert", "record_finding", "get_system_health"),
        trigger_conditions=("incident_created", "escalation_received"),
        decision_policy="incident_response",
        max_concurrent=3,
    ),
]

# ─── DOMAIN B: MODERATION (11-20) ───────────────────────────────────

MODERATION_AGENTS = [
    AgentDef(
        agent_id="mod-001",
        name="Report Triage Worker",
        domain="moderation",
        agent_type="deterministic",
        purpose="Automatically triages incoming reports by priority, type, and severity",
        events=("REPORT_CREATED",),
        tools=("check_user_reports", "check_spam_signals", "record_finding"),
        trigger_conditions=("new_report",),
        decision_policy="priority_classification",
        max_runs_per_hour=60,
    ),
    AgentDef(
        agent_id="mod-002",
        name="Harm Detection Worker",
        domain="moderation",
        agent_type="ai_reasoning",
        purpose="Analyzes reported content for harmful material, policy violations, and safety concerns",
        events=("REPORT_CREATED", "POST_CREATED", "COMMENT_CREATED"),
        tools=("analyze_content_risk", "check_spam_signals", "record_finding"),
        trigger_conditions=("new_report", "high_risk_content"),
        confidence_threshold=0.7,
        max_runs_per_hour=30,
    ),
    AgentDef(
        agent_id="mod-003",
        name="Bullying Detection Worker",
        domain="moderation",
        agent_type="ai_reasoning",
        purpose="Detects bullying and harassment patterns in comments and posts",
        events=("COMMENT_CREATED", "POST_CREATED", "REPORT_CREATED"),
        tools=("analyze_content_risk", "record_finding", "create_alert"),
        trigger_conditions=("new_comment", "report_bullying"),
        confidence_threshold=0.65,
        max_runs_per_hour=40,
    ),
    AgentDef(
        agent_id="mod-004",
        name="Harassment Monitor",
        domain="moderation",
        agent_type="anomaly_detector",
        purpose="Monitors for sustained harassment campaigns targeting specific users",
        events=("REPORT_CREATED", "COMMENT_CREATED", "SUSPICIOUS_ACTIVITY"),
        tools=("read_service_metrics", "check_spam_signals", "create_alert", "record_finding"),
        trigger_conditions=("repeated_reports", "user_targeted"),
        decision_policy="pattern_escalation",
        max_runs_per_hour=20,
    ),
    AgentDef(
        agent_id="mod-005",
        name="Spam Report Worker",
        domain="moderation",
        agent_type="deterministic",
        purpose="Processes spam reports and correlates with spam detection signals",
        events=("REPORT_CREATED", "SPAM_DETECTED"),
        tools=("check_spam_signals", "check_user_reports", "record_finding"),
        trigger_conditions=("spam_report", "spam_cluster"),
        max_runs_per_hour=50,
    ),
    AgentDef(
        agent_id="mod-006",
        name="False Information Review",
        domain="moderation",
        agent_type="ai_reasoning",
        purpose="Reviews flagged content for potential misinformation or misleading claims",
        events=("REPORT_CREATED", "POST_CREATED"),
        tools=("analyze_content_risk", "record_finding"),
        trigger_conditions=("misinfo_report", "high_visibility_content"),
        confidence_threshold=0.8,
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="mod-007",
        name="Duplicate Report Worker",
        domain="moderation",
        agent_type="deterministic",
        purpose="Identifies and consolidates duplicate reports about the same content",
        events=("REPORT_CREATED",),
        tools=("check_user_reports", "detect_duplicates", "record_finding"),
        trigger_conditions=("new_report", "duplicate_suspected"),
        max_runs_per_hour=100,
    ),
    AgentDef(
        agent_id="mod-008",
        name="Duplicate Content Worker",
        domain="moderation",
        agent_type="deterministic",
        purpose="Detects duplicate or near-duplicate posts and suggests merging",
        events=("POST_CREATED",),
        tools=("detect_duplicates", "record_finding"),
        trigger_conditions=("new_post", "similarity_threshold"),
        max_runs_per_hour=50,
    ),
    AgentDef(
        agent_id="mod-009",
        name="Escalation Worker",
        domain="moderation",
        agent_type="coordinator",
        purpose="Escalates complex moderation cases to human moderators with full context",
        events=("REPORT_CREATED", "ABUSE_DETECTED", "SECURITY_ANOMALY"),
        tools=("create_alert", "record_finding"),
        trigger_conditions=("escalation_needed", "ai_uncertain"),
        decision_policy="escalation_rules",
        max_concurrent=5,
    ),
    AgentDef(
        agent_id="mod-010",
        name="Moderation Quality Auditor",
        domain="moderation",
        agent_type="deterministic",
        purpose="Audits moderation actions for consistency, accuracy, and policy compliance",
        events=("REPORT_VERIFIED", "DEPLOYMENT_COMPLETED"),
        tools=("record_finding", "get_system_health"),
        trigger_conditions=("periodic_audit", "moderation_action"),
        max_runs_per_hour=2,
    ),
]

# ─── DOMAIN C: PERFORMANCE (21-30) ──────────────────────────────────

PERFORMANCE_AGENTS = [
    AgentDef(
        agent_id="perf-001",
        name="Frontend Performance Monitor",
        domain="performance",
        agent_type="anomaly_detector",
        purpose="Monitors real user web vitals (LCP, CLS, INP, TTFB) and detects regressions",
        events=("API_REQUEST", "PERFORMANCE_REGRESSION", "DEPLOYMENT_COMPLETED"),
        tools=("read_service_metrics", "get_system_health", "create_alert", "record_finding"),
        trigger_conditions=("vital_regression", "deploy_completed"),
        decision_policy="baseline_comparison",
        max_runs_per_hour=20,
    ),
    AgentDef(
        agent_id="perf-002",
        name="API Latency Monitor",
        domain="performance",
        agent_type="anomaly_detector",
        purpose="Monitors API response times across all endpoints, detects latency spikes",
        events=("API_REQUEST", "LATENCY_SPIKE", "API_ERROR"),
        tools=("read_service_metrics", "get_system_health", "create_alert", "record_finding"),
        trigger_conditions=("latency_spike", "p95_regression"),
        decision_policy="statistical_baseline",
        max_runs_per_hour=30,
    ),
    AgentDef(
        agent_id="perf-003",
        name="Database Performance Worker",
        domain="performance",
        agent_type="anomaly_detector",
        purpose="Monitors database query performance, connection pool health, and slow queries",
        events=("DATABASE_ERROR", "LATENCY_SPIKE", "API_ERROR"),
        tools=("read_database_metrics", "get_system_health", "record_finding"),
        trigger_conditions=("slow_query", "connection_pool_exhaustion", "db_latency_spike"),
        max_runs_per_hour=15,
    ),
    AgentDef(
        agent_id="perf-004",
        name="Cache Optimizer",
        domain="performance",
        agent_type="deterministic",
        purpose="Monitors cache hit ratios, detects inefficiency, recommends cache strategy improvements",
        events=("CACHE_MISS_SPIKE", "LATENCY_SPIKE", "API_REQUEST"),
        tools=("read_cache_metrics", "read_service_metrics", "record_finding"),
        trigger_conditions=("cache_miss_spike", "hit_ratio_drop"),
        decision_policy="threshold_analysis",
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="perf-005",
        name="Query Analyzer",
        domain="performance",
        agent_type="ai_reasoning",
        purpose="Analyzes slow database queries, suggests indexes and query rewrites",
        events=("DATABASE_ERROR", "LATENCY_SPIKE"),
        tools=("read_database_metrics", "analyze_query_plan", "record_finding"),
        trigger_conditions=("slow_query_detected", "n_plus_one_pattern"),
        confidence_threshold=0.7,
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="perf-006",
        name="Queue Optimizer",
        domain="performance",
        agent_type="deterministic",
        purpose="Monitors job queues for backlogs, stuck jobs, and processing bottlenecks",
        events=("QUEUE_BACKLOG", "API_ERROR", "SERVICE_DEGRADED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("queue_depth_high", "job_stuck"),
        max_runs_per_hour=20,
    ),
    AgentDef(
        agent_id="perf-007",
        name="Resource Utilization Monitor",
        domain="performance",
        agent_type="anomaly_detector",
        purpose="Monitors CPU, memory, disk, and network utilization across services",
        events=("CPU_SPIKE", "MEMORY_SPIKE", "SERVICE_DEGRADED"),
        tools=("get_system_health", "read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("resource_spike", "utilization_threshold"),
        max_runs_per_hour=20,
    ),
    AgentDef(
        agent_id="perf-008",
        name="Asset Optimization Worker",
        domain="performance",
        agent_type="deterministic",
        purpose="Monitors bundle sizes, asset loading times, and compression efficiency",
        events=("DEPLOYMENT_COMPLETED", "PERFORMANCE_REGRESSION"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("deploy_completed", "bundle_size_increase"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="perf-009",
        name="Web Vitals Monitor",
        domain="performance",
        agent_type="anomaly_detector",
        purpose="Tracks real-user Core Web Vitals across device types and connections",
        events=("API_REQUEST", "PERFORMANCE_REGRESSION"),
        tools=("read_service_metrics", "get_system_health", "record_finding"),
        trigger_conditions=("vital_regression", "mobile_regression"),
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="perf-010",
        name="Capacity Planner",
        domain="performance",
        agent_type="ai_reasoning",
        purpose="Forecasts capacity needs based on growth trends and current utilization",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_RECOVERED"),
        tools=("read_service_metrics", "get_system_health", "record_finding"),
        trigger_conditions=("periodic_forecast", "capacity_threshold"),
        max_runs_per_hour=1,
        confidence_threshold=0.7,
    ),
]

# ─── DOMAIN D: RELIABILITY (31-40) ──────────────────────────────────

RELIABILITY_AGENTS = [
    AgentDef(
        agent_id="rel-001",
        name="Service Health Monitor",
        domain="reliability",
        agent_type="deterministic",
        purpose="Continuous health checks across all platform services",
        events=("SERVICE_DEGRADED", "SERVICE_RECOVERED", "DEPLOYMENT_COMPLETED"),
        tools=("get_system_health", "create_alert", "record_finding"),
        trigger_conditions=("health_check_failed", "periodic_check"),
        max_runs_per_hour=60,
    ),
    AgentDef(
        agent_id="rel-002",
        name="Error Monitor",
        domain="reliability",
        agent_type="anomaly_detector",
        purpose="Detects error rate spikes and correlates with recent changes",
        events=("API_ERROR", "DATABASE_ERROR", "ERROR_RATE_SPIKE"),
        tools=("read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("error_spike", "new_error_type"),
        decision_policy="rate_of_change",
        max_runs_per_hour=30,
    ),
    AgentDef(
        agent_id="rel-003",
        name="Failed Job Worker",
        domain="reliability",
        agent_type="deterministic",
        purpose="Detects and retries failed background jobs, manages dead-letter queue",
        events=("QUEUE_BACKLOG", "SERVICE_DEGRADED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("failed_job_detected", "retry_exhausted"),
        max_runs_per_hour=20,
    ),
    AgentDef(
        agent_id="rel-004",
        name="Retry Coordinator",
        domain="reliability",
        agent_type="coordinator",
        purpose="Coordinates retry strategies across services with exponential backoff",
        events=("API_ERROR", "DATABASE_ERROR", "SERVICE_DEGRADED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("transient_failure", "retry_needed"),
        decision_policy="backoff_strategy",
        max_concurrent=5,
    ),
    AgentDef(
        agent_id="rel-005",
        name="Dependency Monitor",
        domain="reliability",
        agent_type="deterministic",
        purpose="Monitors health and latency of external dependencies (Supabase, Redis, LLM APIs)",
        events=("SERVICE_DEGRADED", "API_ERROR", "LATENCY_SPIKE"),
        tools=("read_service_metrics", "get_system_health", "create_alert", "record_finding"),
        trigger_conditions=("dependency_degraded", "dependency_timeout"),
        max_runs_per_hour=30,
    ),
    AgentDef(
        agent_id="rel-006",
        name="Incident Detector",
        domain="reliability",
        agent_type="anomaly_detector",
        purpose="Detects incidents by correlating multiple failure signals",
        events=("SERVICE_DEGRADED", "ERROR_RATE_SPIKE", "CPU_SPIKE", "MEMORY_SPIKE"),
        tools=("get_system_health", "create_alert", "record_finding"),
        trigger_conditions=("multi_signal_correlation", "severity_escalation"),
        decision_policy="incident_classification",
        max_runs_per_hour=15,
    ),
    AgentDef(
        agent_id="rel-007",
        name="Recovery Worker",
        domain="reliability",
        agent_type="deterministic",
        purpose="Executes recovery procedures after service degradation is resolved",
        events=("SERVICE_RECOVERED", "DEPLOYMENT_COMPLETED"),
        tools=("verify_fix", "get_system_health", "record_finding"),
        trigger_conditions=("service_recovered", "post_incident"),
        verification_method="health_check",
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="rel-008",
        name="Deployment Verifier",
        domain="reliability",
        agent_type="deterministic",
        purpose="Verifies deployments by running health checks and smoke tests",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("verify_fix", "get_system_health", "create_alert", "record_finding"),
        trigger_conditions=("new_deployment",),
        verification_method="smoke_test",
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="rel-009",
        name="Configuration Drift Detector",
        domain="reliability",
        agent_type="deterministic",
        purpose="Detects when configuration drifts from expected baseline",
        events=("CONFIGURATION_CHANGED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("config_change", "drift_detected"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="rel-010",
        name="Reliability Coordinator",
        domain="reliability",
        agent_type="coordinator",
        purpose="Coordinates multi-agent reliability response, prioritizes incident resolution",
        events=("SERVICE_DEGRADED", "ERROR_RATE_SPIKE", "INCIDENT_CREATED"),
        tools=("create_alert", "get_system_health", "record_finding"),
        trigger_conditions=("incident_created", "multi_service_failure"),
        decision_policy="incident_response",
        max_concurrent=3,
    ),
]

# ─── DOMAIN E: DATA (41-50) ─────────────────────────────────────────

DATA_AGENTS = [
    AgentDef(
        agent_id="data-001",
        name="Data Integrity Worker",
        domain="data",
        agent_type="deterministic",
        purpose="Verifies data integrity constraints, detects orphaned records and inconsistencies",
        events=("POST_CREATED", "COMMENT_CREATED", "DEPLOYMENT_COMPLETED"),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("integrity_check", "periodic_audit"),
        max_runs_per_hour=4,
    ),
    AgentDef(
        agent_id="data-002",
        name="Missing Data Detector",
        domain="data",
        agent_type="deterministic",
        purpose="Detects required fields that are missing or null in critical tables",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("periodic_check", "schema_change"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="data-003",
        name="Duplicate Data Worker",
        domain="data",
        agent_type="deterministic",
        purpose="Finds and reports duplicate records across critical tables",
        events=("POST_CREATED", "DEPLOYMENT_COMPLETED"),
        tools=("detect_duplicates", "read_database_metrics", "record_finding"),
        trigger_conditions=("periodic_check", "duplicate_suspected"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="data-004",
        name="Stale Data Worker",
        domain="data",
        agent_type="deterministic",
        purpose="Identifies stale or expired data that should be cleaned up",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("periodic_check", "data_age_threshold"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="data-005",
        name="Consistency Auditor",
        domain="data",
        agent_type="deterministic",
        purpose="Audits cross-table data consistency (e.g., post comment_count vs actual comments)",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("periodic_audit", "consistency_check"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="data-006",
        name="Database Cleanup Worker",
        domain="data",
        agent_type="deterministic",
        purpose="Safely cleans up expired sessions, temporary data, and orphaned records",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("periodic_cleanup", "expired_data_detected"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="data-007",
        name="Index Health Worker",
        domain="data",
        agent_type="deterministic",
        purpose="Monitors index usage, detects missing or unused indexes",
        events=("DATABASE_ERROR", "LATENCY_SPIKE", "DEPLOYMENT_COMPLETED"),
        tools=("read_database_metrics", "analyze_query_plan", "record_finding"),
        trigger_conditions=("slow_query", "index_scan_heavy"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="data-008",
        name="Backup Verification Worker",
        domain="data",
        agent_type="deterministic",
        purpose="Verifies backup integrity and restore capability",
        events=("BACKUP_COMPLETED", "BACKUP_FAILED"),
        tools=("verify_fix", "record_finding"),
        trigger_conditions=("backup_completed", "periodic_verify"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="data-009",
        name="Migration Auditor",
        domain="data",
        agent_type="deterministic",
        purpose="Audits database migrations for safety, reversibility, and performance impact",
        events=("DEPLOYMENT_COMPLETED", "CONFIGURATION_CHANGED"),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("migration_applied",),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="data-010",
        name="Data Quality Coordinator",
        domain="data",
        agent_type="coordinator",
        purpose="Coordinates data quality checks across all data domain workers",
        events=("DEPLOYMENT_COMPLETED", "DATABASE_ERROR"),
        tools=("get_system_health", "record_finding"),
        trigger_conditions=("quality_check_needed", "multi_source_discrepancy"),
        max_concurrent=2,
    ),
]

# ─── DOMAIN F: USER EXPERIENCE (51-60) ──────────────────────────────

UX_AGENTS = [
    AgentDef(
        agent_id="ux-001",
        name="UX Friction Detector",
        domain="user_experience",
        agent_type="anomaly_detector",
        purpose="Detects UX friction from error rates, abandoned flows, and interaction patterns",
        events=("API_ERROR", "USER_FEEDBACK", "PERFORMANCE_REGRESSION"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("error_rate_high", "flow_abandonment"),
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="ux-002",
        name="Accessibility Auditor",
        domain="user_experience",
        agent_type="deterministic",
        purpose="Audits accessibility compliance across user-facing pages",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("deploy_completed", "periodic_audit"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="ux-003",
        name="Mobile Experience Monitor",
        domain="user_experience",
        agent_type="anomaly_detector",
        purpose="Monitors mobile-specific UX metrics and touch interaction quality",
        events=("API_REQUEST", "PERFORMANCE_REGRESSION"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("mobile_regression", "touch_target_issue"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="ux-004",
        name="Broken Flow Detector",
        domain="user_experience",
        agent_type="deterministic",
        purpose="Detects broken user flows (404s, failed API calls in critical paths)",
        events=("API_ERROR", "USER_FEEDBACK"),
        tools=("read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("404_spike", "critical_path_error"),
        max_runs_per_hour=15,
    ),
    AgentDef(
        agent_id="ux-005",
        name="Search Quality Worker",
        domain="user_experience",
        agent_type="deterministic",
        purpose="Monitors search query performance, relevance, and zero-result rates",
        events=("SEARCH_PERFORMED", "API_ERROR"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("zero_result_spike", "search_latency_high"),
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="ux-006",
        name="Notification Health Worker",
        domain="user_experience",
        agent_type="deterministic",
        purpose="Monitors notification delivery rates and quality",
        events=("USER_FEEDBACK", "API_ERROR"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("notification_failure", "delivery_drop"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="ux-007",
        name="Form Validation Monitor",
        domain="user_experience",
        agent_type="deterministic",
        purpose="Monitors form submission error rates and validation failures",
        events=("API_ERROR", "USER_FEEDBACK"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("form_error_spike", "validation_failure"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="ux-008",
        name="Feedback Analyzer",
        domain="user_experience",
        agent_type="ai_reasoning",
        purpose="Analyzes user feedback for actionable insights and pain points",
        events=("USER_FEEDBACK", "REPORT_CREATED"),
        tools=("record_finding"),
        trigger_conditions=("feedback_received", "feedback_cluster"),
        confidence_threshold=0.6,
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="ux-009",
        name="User Journey Analyst",
        domain="user_experience",
        agent_type="ai_reasoning",
        purpose="Analyzes user journey patterns to identify drop-off points and improvement opportunities",
        events=("USER_CREATED", "POST_CREATED", "USER_FEEDBACK"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_analysis", "journey_anomaly"),
        max_runs_per_hour=1,
        confidence_threshold=0.7,
    ),
    AgentDef(
        agent_id="ux-010",
        name="UX Coordinator",
        domain="user_experience",
        agent_type="coordinator",
        purpose="Coordinates UX improvement initiatives across all UX domain workers",
        events=("USER_FEEDBACK", "PERFORMANCE_REGRESSION"),
        tools=("get_system_health", "record_finding"),
        trigger_conditions=("ux_issue_cluster", "improvement_needed"),
        max_concurrent=2,
    ),
]

# ─── DOMAIN G: COMMUNITY (61-70) ────────────────────────────────────

COMMUNITY_AGENTS = [
    AgentDef(
        agent_id="com-001",
        name="Community Health Monitor",
        domain="community",
        agent_type="deterministic",
        purpose="Monitors overall community health metrics: engagement, sentiment, activity levels",
        events=("POST_CREATED", "COMMENT_CREATED", "POLL_VOTED", "USER_CREATED"),
        tools=("get_system_health", "read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_check", "health_degradation"),
        max_runs_per_hour=4,
    ),
    AgentDef(
        agent_id="com-002",
        name="Engagement Analyst",
        domain="community",
        agent_type="deterministic",
        purpose="Analyzes engagement patterns: reaction rates, comment depth, discussion quality",
        events=("POST_CREATED", "COMMENT_CREATED", "POLL_VOTED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_analysis", "engagement_anomaly"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="com-003",
        name="Trending Issue Detector",
        domain="community",
        agent_type="anomaly_detector",
        purpose="Detects emerging issues and trending topics from post velocity and engagement",
        events=("POST_CREATED", "COMMENT_CREATED", "REPORT_CREATED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("velocity_spike", "engagement_spike"),
        max_runs_per_hour=20,
    ),
    AgentDef(
        agent_id="com-004",
        name="Category Health Worker",
        domain="community",
        agent_type="deterministic",
        purpose="Monitors health of individual categories: response times, resolution rates",
        events=("POST_CREATED", "DEPLOYMENT_COMPLETED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("category_anomaly", "periodic_check"),
        max_runs_per_hour=4,
    ),
    AgentDef(
        agent_id="com-005",
        name="Discussion Quality Worker",
        domain="community",
        agent_type="deterministic",
        purpose="Monitors discussion quality signals: comment depth, constructive engagement",
        events=("COMMENT_CREATED", "POST_CREATED"),
        tools=("analyze_content_risk", "record_finding"),
        trigger_conditions=("low_quality_cluster", "periodic_check"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="com-006",
        name="Community Risk Analyst",
        domain="community",
        agent_type="ai_reasoning",
        purpose="Identifies community-level risks: disengagement, trust erosion, toxic trends",
        events=("REPORT_CREATED", "USER_FEEDBACK", "COMMENT_CREATED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("risk_signal", "trust_indicator_drop"),
        confidence_threshold=0.7,
        max_runs_per_hour=3,
    ),
    AgentDef(
        agent_id="com-007",
        name="Participation Analyst",
        domain="community",
        agent_type="deterministic",
        purpose="Tracks new vs returning participant ratios and participation trends",
        events=("USER_CREATED", "POST_CREATED", "COMMENT_CREATED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_analysis"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="com-008",
        name="Feedback Pattern Worker",
        domain="community",
        agent_type="deterministic",
        purpose="Identifies patterns in user feedback for systemic issues",
        events=("USER_FEEDBACK", "REPORT_CREATED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("feedback_pattern", "periodic_analysis"),
        max_runs_per_hour=3,
    ),
    AgentDef(
        agent_id="com-009",
        name="Community Insight Worker",
        domain="community",
        agent_type="ai_reasoning",
        purpose="Generates actionable community insights from aggregated signals",
        events=("USER_FEEDBACK", "POST_CREATED", "POLL_VOTED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("insight_opportunity", "periodic_analysis"),
        confidence_threshold=0.65,
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="com-010",
        name="Community Coordinator",
        domain="community",
        agent_type="coordinator",
        purpose="Coordinates community health initiatives across domain workers",
        events=("REPORT_CREATED", "USER_FEEDBACK", "SERVICE_RECOVERED"),
        tools=("get_system_health", "record_finding"),
        trigger_conditions=("community_issue", "coordination_needed"),
        max_concurrent=2,
    ),
]

# ─── DOMAIN H: ANALYTICS (71-80) ────────────────────────────────────

ANALYTICS_AGENTS = [
    AgentDef(
        agent_id="ana-001",
        name="Anomaly Analytics Worker",
        domain="analytics",
        agent_type="anomaly_detector",
        purpose="Detects statistical anomalies across all platform metrics",
        events=("API_REQUEST", "PERFORMANCE_REGRESSION", "ERROR_RATE_SPIKE"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("anomaly_detected", "metric_deviation"),
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="ana-002",
        name="KPI Monitor",
        domain="analytics",
        agent_type="deterministic",
        purpose="Tracks key performance indicators against targets",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_RECOVERED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_check", "kpi_breach"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ana-003",
        name="Trend Detector",
        domain="analytics",
        agent_type="deterministic",
        purpose="Detects emerging trends in content, engagement, and platform usage",
        events=("POST_CREATED", "USER_CREATED", "SEARCH_PERFORMED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("trend_detected", "periodic_analysis"),
        max_runs_per_hour=4,
    ),
    AgentDef(
        agent_id="ana-004",
        name="Forecasting Worker",
        domain="analytics",
        agent_type="ai_reasoning",
        purpose="Forecasts future platform metrics based on historical trends",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_RECOVERED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_forecast", "growth_milestone"),
        max_runs_per_hour=1,
        confidence_threshold=0.7,
    ),
    AgentDef(
        agent_id="ana-005",
        name="Capacity Forecast Worker",
        domain="analytics",
        agent_type="deterministic",
        purpose="Forecasts infrastructure capacity needs based on growth patterns",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "get_system_health", "record_finding"),
        trigger_conditions=("capacity_threshold", "periodic_forecast"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="ana-006",
        name="Engagement Forecast Worker",
        domain="analytics",
        agent_type="deterministic",
        purpose="Forecasts engagement metrics for planning and goal tracking",
        events=("POST_CREATED", "COMMENT_CREATED", "POLL_VOTED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_forecast"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="ana-007",
        name="Moderation Forecast Worker",
        domain="analytics",
        agent_type="deterministic",
        purpose="Forecasts moderation workload and capacity needs",
        events=("REPORT_CREATED", "COMMENT_CREATED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_forecast", "workload_spike"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="ana-008",
        name="Risk Forecast Worker",
        domain="analytics",
        agent_type="deterministic",
        purpose="Forecasts platform risk levels based on current signals",
        events=("SECURITY_ANOMALY", "REPORT_CREATED", "USER_FEEDBACK"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_forecast", "risk_elevation"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ana-009",
        name="Operational Analytics Worker",
        domain="analytics",
        agent_type="deterministic",
        purpose="Aggregates operational metrics for admin dashboards",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "get_system_health", "record_finding"),
        trigger_conditions=("periodic_aggregation", "dashboard_refresh"),
        max_runs_per_hour=4,
    ),
    AgentDef(
        agent_id="ana-010",
        name="Analytics Coordinator",
        domain="analytics",
        agent_type="coordinator",
        purpose="Coordinates analytics initiatives and cross-domain metric reporting",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("get_system_health", "record_finding"),
        trigger_conditions=("analytics_needed", "cross_domain_insight"),
        max_concurrent=2,
    ),
]

# ─── DOMAIN I: PLATFORM OPS (81-90) ─────────────────────────────────

PLATFORM_OPS_AGENTS = [
    AgentDef(
        agent_id="ops-001",
        name="Scheduled Maintenance Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Executes scheduled maintenance tasks: cleanup, optimization, health checks",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "read_cache_metrics", "record_finding"),
        trigger_conditions=("scheduled_maintenance", "periodic_check"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ops-002",
        name="Cache Maintenance Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Maintains cache health: detects stale entries, oversized entries, and cold caches",
        events=("CACHE_MISS_SPIKE", "DEPLOYMENT_COMPLETED"),
        tools=("read_cache_metrics", "record_finding"),
        trigger_conditions=("cache_health_issue", "periodic_check"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="ops-003",
        name="Temporary Data Cleanup",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Cleans up expired temporary data, sessions, and ephemeral records",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("expired_data_detected", "periodic_cleanup"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ops-004",
        name="Storage Monitor",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Monitors storage utilization and growth rates",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "get_system_health", "record_finding"),
        trigger_conditions=("storage_threshold", "periodic_check"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ops-005",
        name="Queue Maintenance Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Monitors and maintains job queue health, purges dead jobs",
        events=("QUEUE_BACKLOG", "SERVICE_DEGRADED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("queue_health_issue", "periodic_check"),
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="ops-006",
        name="Index Maintenance Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Monitors database index health and recommends maintenance",
        events=("DATABASE_ERROR", "LATENCY_SPIKE"),
        tools=("read_database_metrics", "analyze_query_plan", "record_finding"),
        trigger_conditions=("index_degradation", "periodic_check"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ops-007",
        name="Session Cleanup Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Cleans up expired sessions and stale authentication tokens",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_database_metrics", "record_finding"),
        trigger_conditions=("expired_sessions", "periodic_cleanup"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ops-008",
        name="Resource Cleanup Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Frees unused resources: expired cache keys, orphaned files, stale connections",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_cache_metrics", "read_database_metrics", "record_finding"),
        trigger_conditions=("resource_cleanup_needed", "periodic_cleanup"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="ops-009",
        name="System Optimization Worker",
        domain="platform_ops",
        agent_type="deterministic",
        purpose="Applies safe system optimizations based on performance data",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_RECOVERED"),
        tools=("get_system_health", "read_service_metrics", "record_finding"),
        trigger_conditions=("optimization_opportunity", "periodic_review"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="ops-010",
        name="Operations Coordinator",
        domain="platform_ops",
        agent_type="coordinator",
        purpose="Coordinates platform operations across all ops domain workers",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_DEGRADED", "SERVICE_RECOVERED"),
        tools=("get_system_health", "record_finding"),
        trigger_conditions=("ops_coordination_needed", "multi_task_conflict"),
        max_concurrent=3,
    ),
]

# ─── DOMAIN J: AI GOVERNANCE (91-100) ────────────────────────────────

AI_GOVERNANCE_AGENTS = [
    AgentDef(
        agent_id="gov-001",
        name="Model Quality Monitor",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Monitors LLM response quality, latency, and reliability across providers",
        events=("API_ERROR", "SERVICE_DEGRADED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("model_quality_drop", "provider_error"),
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="gov-002",
        name="Hallucination Detector",
        domain="ai_governance",
        agent_type="ai_reasoning",
        purpose="Detects potential hallucinations in AI-generated content by cross-referencing with platform data",
        events=("POST_CREATED", "USER_FEEDBACK"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("ai_content_generated", "quality_check_needed"),
        confidence_threshold=0.7,
        max_runs_per_hour=5,
    ),
    AgentDef(
        agent_id="gov-003",
        name="Agent Reliability Monitor",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Monitors reliability of all AI agents: failure rates, response times, resource usage",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_check", "agent_failure_spike"),
        max_runs_per_hour=4,
    ),
    AgentDef(
        agent_id="gov-004",
        name="Tool Failure Monitor",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Monitors tool execution success/failure rates across all agents",
        events=("API_ERROR", "SERVICE_DEGRADED"),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("tool_failure_spike", "periodic_check"),
        max_runs_per_hour=10,
    ),
    AgentDef(
        agent_id="gov-005",
        name="Confidence Auditor",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Audits agent confidence scores to detect overconfidence or underconfidence patterns",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("confidence_anomaly", "periodic_audit"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="gov-006",
        name="Agent Cost Monitor",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Tracks LLM API costs per agent, domain, and time period",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("cost_threshold", "periodic_report"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="gov-007",
        name="Agent Performance Evaluator",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Evaluates agent performance: accuracy, usefulness, false positive/negative rates",
        events=("DEPLOYMENT_COMPLETED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("periodic_evaluation", "performance_drop"),
        max_runs_per_hour=1,
    ),
    AgentDef(
        agent_id="gov-008",
        name="Policy Compliance Worker",
        domain="ai_governance",
        agent_type="deterministic",
        purpose="Verifies all agent actions comply with configured policies and safety rules",
        events=("CONFIGURATION_CHANGED",),
        tools=("read_service_metrics", "record_finding"),
        trigger_conditions=("policy_change", "compliance_check"),
        max_runs_per_hour=2,
    ),
    AgentDef(
        agent_id="gov-009",
        name="Workforce Coordinator",
        domain="ai_governance",
        agent_type="coordinator",
        purpose="Coordinates cross-domain workforce activities, prevents conflicts",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_DEGRADED"),
        tools=("get_system_health", "record_finding"),
        trigger_conditions=("coordination_needed", "conflict_detected"),
        max_concurrent=3,
    ),
    AgentDef(
        agent_id="gov-010",
        name="Workforce Supervisor",
        domain="ai_governance",
        agent_type="coordinator",
        purpose="Supervises the entire workforce: detects stuck workers, rebalances load, enforces budgets",
        events=("DEPLOYMENT_COMPLETED", "SERVICE_DEGRADED", "CONFIGURATION_CHANGED"),
        tools=("get_system_health", "read_service_metrics", "create_alert", "record_finding"),
        trigger_conditions=("worker_stuck", "budget_exceeded", "periodic_supervision"),
        decision_policy="supervisor_override",
        max_concurrent=1,
    ),
]

# ─── ALL AGENTS ──────────────────────────────────────────────────────

ALL_AGENTS: list[AgentDef] = (
    SECURITY_AGENTS
    + MODERATION_AGENTS
    + PERFORMANCE_AGENTS
    + RELIABILITY_AGENTS
    + DATA_AGENTS
    + UX_AGENTS
    + COMMUNITY_AGENTS
    + ANALYTICS_AGENTS
    + PLATFORM_OPS_AGENTS
    + AI_GOVERNANCE_AGENTS
)

AGENT_MAP: dict[str, AgentDef] = {a.agent_id: a for a in ALL_AGENTS}

DOMAIN_MAP: dict[str, list[AgentDef]] = {}
for _a in ALL_AGENTS:
    DOMAIN_MAP.setdefault(_a.domain, []).append(_a)

# ─── Event → Agent routing ───────────────────────────────────────────

def agents_for_event(event_type: str) -> list[AgentDef]:
    """Return all agents that should be notified of a given event type."""
    result = []
    for agent in ALL_AGENTS:
        if event_type in agent.events:
            result.append(agent)
    return result
